INSERT INTO Games (nome) VALUES ('The Legend of Zelda: Breath of the Wild');
INSERT INTO Games (nome) VALUES ('Red Dead Redemption 2');
INSERT INTO Games (nome) VALUES ('The Witcher 3: Wild Hunt');
INSERT INTO Games (nome) VALUES ('God of War');
INSERT INTO Games (nome) VALUES ('Spider-Man: Miles Morales');
INSERT INTO Games (nome) VALUES ('Cyberpunk 2077');
INSERT INTO Games (nome) VALUES ('Assassins Creed Valhalla');
INSERT INTO Games (nome) VALUES ('Call of Duty: Warzone');
INSERT INTO Games (nome) VALUES ('FIFA 22');
INSERT INTO Games (nome) VALUES ('Minecraft');
INSERT INTO Games (nome) VALUES ('Fortnite');
INSERT INTO Games (nome) VALUES ('Among Us');
INSERT INTO Games (nome) VALUES ('Animal Crossing: New Horizons');
INSERT INTO Games (nome) VALUES ('Final Fantasy VII Remake');
INSERT INTO Games (nome) VALUES ('Genshin Impact');
